#ifndef EXTENSIONSYSTEM_GLOBAL_H
#define EXTENSIONSYSTEM_GLOBAL_H

#include <QtCore/qglobal.h>

#define DECL_EXPORT Q_DECL_EXPORT
#define DECL_IMPORT Q_DECL_IMPORT

#if defined(EXTENSIONSYSTEM_LIBRARY)
#  define EXTENSIONSYSTEM_DECL DECL_EXPORT
#else
#  define EXTENSIONSYSTEM_DECL DECL_IMPORT
#endif

#endif // EXTENSIONSYSTEM_GLOBAL_H
